### ISSUE TITLE
Swift Package Manager support?

### ISSUE THREAD

**Issue by danielbyon** [Tealium/tealium-swift#109]
Could we get SPM support? We're considering moving away from Carthage, now that SPM is supported for iOS/tvOS projects

**Comment by craigrouse** [comment]
@danielbyon I totally understand why you'd want to switch to SPM. We actually built a Swift package file for the current beta release, but unfortunately I discovered during the process that SPM can't handle any mixed Swift/Objective-C code. We have a very small amount of Objective-C in the library, which unfortunately is currently preventing us from supporting SPM. The good news is that it should be fairly simple for us to refactor this into Swift, so we'll aim to get SPM support into an upcoming release very soon. Watch this space!

**Comment by JackoPlane** [comment]
@craigrouse Has there been any update on getting SPM support merged?

**Comment by craigrouse** [comment]
@JackoPlane no definite timescale, but we are actively working on it. Will post back here as soon as we have any news.

**Comment by alexruperez** [comment]
👍 +1

**Comment by craigrouse** [comment]
@danielbyon @JackoPlane @alexruperez SPM is now supported in 1.9.0.

There are just 2 modules that we couldn't support at this time due to SPM limitations around mixed sources: Autotracking and Crash. We hope to resolve this in a future release, and those entries are left commented out in the Package.swift for this reason. Unfortunately, there's been a slight technical issue with the documentation being published (docs.tealium.com/platforms/ios-swift), but this will be resolved later today. Please be sure to read the release notes before upgrading: https://github.com/Tealium/tealium-swift/releases/tag/1.9.0

We look forward to any feedback you may have on our SPM package; so far, we've found it to be far more reliable than CocoaPods or Carthage, and incredibly fast. Hopefully you'll notice this also! Enjoy.

**Comment by danielbyon** [comment]
Integrated this into our app, our builds are so much faster than Carthage, thanks for this!

**Comment by craigrouse** [comment]
Very happy to hear that @danielbyon! That's exactly what we've found. Thanks for sharing.
