### ISSUE TITLE
[TEALIUM SWIFT]: Crash on TealiumPublishSettingsRetriever.swift - Line 160

### ISSUE THREAD

**Issue by sivamoorthykutty** [Tealium/tealium-swift#141]
I get the crash on TealiumPublishSettingsRetriever.swift class file.
Find the crash report from crash analytics.

Crashed: NSOperationQueue 0x10f265980 (QOS: UNSPECIFIED)
0  TealiumSwift                   0x1009747a4 TealiumPublishSettingsRetriever.getPublishSettings(from:) + 160 (TealiumPublishSettingsRetriever.swift:160)
1  TealiumSwift                   0x10097423c closure #1 in TealiumPublishSettingsRetriever.getRemoteSettings(url:lastFetch:completion:) + 132 (TealiumPublishSettingsRetriever.swift:132)
2  TealiumSwift                   0x10099ed4c thunk for @escaping @callee_guaranteed (@guaranteed Data?, @guaranteed NSURLResponse?, @guaranteed Error?) -> () + 4318752076 (<compiler-generated>:4318752076)
3  WSIRegistryFramework           0x101038858 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke.100 + 41236
4  WSIRegistryFramework           0x101038858 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke.100 + 41236
5  CFNetwork                      0x1a7017e88 CFNetServiceBrowserSearchForServices + 96332
6  CFNetwork                      0x1a7028cb8 _CFHTTPMessageSetResponseProxyURL + 8176
7  Foundation                     0x1a412c88c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
8  Foundation                     0x1a402e7cc -[NSBlockOperation main] + 104
9  Foundation                     0x1a412ebcc __NSOPERATION_IS_INVOKING_MAIN__ + 24
10 Foundation                     0x1a402e4a4 -[NSOperation start] + 752
11 Foundation                     0x1a412f5f8 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
12 Foundation                     0x1a412f0b8 __NSOQSchedule_f + 184
13 libdispatch.dylib              0x1a3a04db4 _dispatch_block_async_invoke2 + 144
14 libdispatch.dylib              0x1a39f833c _dispatch_client_callout + 20
15 libdispatch.dylib              0x1a39faaf8 _dispatch_continuation_pop + 408
16 libdispatch.dylib              0x1a39fa258 _dispatch_async_redirect_invoke + 588
17 libdispatch.dylib              0x1a3a075c0 _dispatch_root_queue_drain + 348
18 libdispatch.dylib              0x1a3a07d9c _dispatch_worker_thread2 + 116
19 libsystem_pthread.dylib        0x1a3a5f6d8 _pthread_wqthread + 216
20 libsystem_pthread.dylib        0x1a3a659c8 start_wqthread + 8

**Comment by craigrouse** [comment]
@sivamoorthykutty Thanks for the crash report, and sorry you've experienced this issue. We identified the cause and I think you've also been in touch with our support team who have helped to resolve this for you. The configuration on our CDN that initially caused this issue has been fixed, and additionally, we are going to add some additional checks and balances in the code to protect against non-standard/unexpected file contents so this situation doesn't happen in future.

**Comment by FranzBusch** [comment]
We are seeing the same crash happening in our application. Could you please explain what the underlying problem was and if it is already fixed?

**Comment by craigrouse** [comment]
@FranzBusch The problem was a configuration on our CDN that caused some performance testing code to be injected into the head of the file we read in the mobile SDK to retrieve the mobile configuration settings. Since this code wouldn't normally be present in that file, the code we use in the SDK to parse the file wasn't set up to deal with the extra content. This has now been rectified, both on the CDN and also in the SDK, and a new minor release will be out very soon to protect against similar incidents in future. We have also added extra unit tests to test this part of the code with non-standard content. Apologies for the obvious inconvenience to you and your users.

**Comment by craigrouse** [comment]
@sivamoorthykutty @FranzBusch we have just released [1.9.5](https://github.com/Tealium/tealium-swift/releases/tag/1.9.5), which resolves this issue. The underlying configuration that caused the problem was addressed immediately without requiring an SDK upgrade, but this release is a permanent fix that will prevent a recurrence in future. If you require any further information in relation to this, please speak to the Tealium support team (support@tealium.com).
