### ISSUE TITLE
Visitor ID reset after SDK upgrade

### ISSUE THREAD

**Issue by JanIceTea** [Tealium/tealium-swift#203]
Hi,
we've recently switch from the Obj-C library to the Swift version and it seems that the visitor IDs have been reset. Can you confirm such a behaviour? I thought that the visitor id would be static until a reset has been forced.

**Comment by jameskeith** [comment]
Hi @JanIceTea 

Could you confirm which versions of Obj-C SDK and Swift SDK you migrated from/to? 

The expected behaviour is as you have described, that the Visitor ID should remain consistent between migrations, however there was a known issue (specifically related to the iOS 14.5 I believe) and we released a fix for it in [v2.3.2](https://github.com/Tealium/tealium-swift/releases/tag/2.3.2)

**Comment by JanIceTea** [comment]
We've moved from Obj-C 5.6.5 (bundle version) to Swift: 2.3.0. Do we need to update to 2.3.2?

**Comment by craigrouse** [comment]
@JanIceTea I just wanted to chime in on this, as @jameskeith kindly picked it up while I was out of the office. Upgrading from ObjC to Swift should migrate the visitor ID and other persistent data automatically. The issue with 2.3.0 presented itself in certain cases where the device was updated to the latest OS, but if you upgraded very recently, this is unlikely to cause an issue for your users. 

I have, however, identified an issue that would cause this. There's an override flag available to _prevent_ data from being migrated  - `config.shouldMigratePersistentData = false`. This was intended to be defaulted to `true` if not provided, but is in fact defaulted to `false`. If you set this value to `true` explicitly before you initialize Tealium, the data will be migrated from the ObjC SDK. If you would like to recover the previous visitor IDs and persistent data, you can set this value to `true`, and the data should still be migrated successfully, but you would have to evaluate the impact of this, since your users would revert to their original visitor ID. 

We will update the logic so that this defaults to `true` in future, as that was the intention. Sorry this has caused a problem for you.
