### ISSUE TITLE
[TEALIUM SWIFT BUG]: can not track deeplinking when iOS version bigger than 13.0 but don't use UISceneDelegate.

### ISSUE THREAD

**Issue by xiongyoudou** [Tealium/tealium-swift#304]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) ]: 15.1.1
Xcode version [Xcode>: 14.2
Swift version ]: 5.4.2
Tealium Swift library version [e.g. 1.6.7]: 2.9.1(also debug the latest source code)
Dependency manager [None/Carthage/CocoaPods]:
Dependency manager version: 

**Describe the bug**
We know the tracking of deeplinking is enabled as default, and I can see the related logics in TealiumDelegateProxy class.
But actually it's not working on my project, the tracking can not be tracked.

**Does a workaround exist?**
<img width="720" alt="截屏2023-06-02 下午4 23 49" src="https://github.com/Tealium/tealium-swift/assets/2812119/38abfb06-3728-4bd5-896b-5d081ec0545a">

**To Reproduce**
Make some code changes on the sample app, use UIappdelegate to handle the life cycle events instead of UISceneDelegate
1.  delete configuration in info.plist
![image](https://github.com/Tealium/tealium-swift/assets/2812119/ff69c020-8ed7-4177-84b9-67ecebe6787e)
2. delete the session configuration function
![image](https://github.com/Tealium/tealium-swift/assets/2812119/cf41e380-993c-478f-a404-cd84b1bcd1fd)
After these code change, continuelly add an url scheme to test:
<img width="722" alt="截屏2023-06-02 下午4 32 45" src="https://github.com/Tealium/tealium-swift/assets/2812119/35e20841-dd64-4124-bf0d-ebc2569375b3">

 Finally can run the sample app and use the url scheme to test whether the delegate functions can be called in TealiumDelegateProxy class.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiongyoudou** [comment]
Hi @craigrouse  thanks for your quick reply. I just supplemented some more information
I use the UIKit based on UIApplication delegate, but not the UISceneDelegate.

**Comment by craigrouse** [comment]
@xiongyoudou we'll take a look and see if we can figure out what's going on.

**Comment by Enricoza** [comment]
@xiongyoudou thank you again for opening this issue and for the details provided. 

Following the steps to reproduce that you provided I was able to reproduce the issue, but I believe that applying your steps actually result in an invalid configuration of the `AppDelegate` and `SceneDelegate`.
In order to properly remove the `SceneDelegate` and provide a fully functional `AppDelegate`, in addition to your steps, you also need to remove the `application(:didDiscardSceneSessions:)` implementation on line 27 of our sample `AppDelegate`.
Once you do that our automatic deeplinking tracking should start to work back as expected.

To be noted that if you don't remove this other method, even the `application(:open:options:)` method of the `AppDelegate` won't be called. And this is true even if Tealium is entirely stripped off of the sample application.
As soon as you remove the `didDiscardSceneSessions` method, the `application(:open:options:)` starts to get called again, leading me to think that some improper mix of `AppDelegate` and `SceneDelegate` here is the cause of the issue. 

Let us know if you are also able to verify the same results that I had in my tests and if you still have issues on your app after trying this fix.

**Comment by xiongyoudou** [comment]
Thanks @craigrouse @Enricoza  I will try it again on sample and on my project to see whether it works for me.
I will leave comments here if got any result.

**Comment by xiongyoudou** [comment]
Thanks for your help, I think it's our project's configuration lead to this issue, I will close it.
