### ISSUE TITLE
[TEALIUM SWIFT BUG]: Swift Package Manager limitations: 

### ISSUE THREAD

**Issue by salvatoreboemia** [Tealium/tealium-swift#306]
Hi 

news about this limitation?

- https://docs.tealium.com/platforms/ios-swift/install/

> Swift Package Manager has the following limitations:
> 
> - Due to lack of mixed-language source in a single target, the [CrashReporter](https://docs.tealium.com/platforms/ios-swift/module-list/crash-reporter/) and [AutoTracking](https://docs.tealium.com/platforms/ios-swift/module-list/autotracking/) modules are not supported through the Swift Package Manager. Verify that you do not need these modules before using Swift Package Manager.
> 
> - Restricting a target within a package to a specific platform is not possible. Modules such as [TagManagement](https://docs.tealium.com/platforms/ios-swift/module-list/tag-management/), which are only supported for iOS, also become available to non-iOS targets. Adding one of these modules to an non-iOS target causes the compiler throws errors due to unavailable system libraries.

Thanks

**Comment by Enricoza** [comment]
Hi @salvatoreboemia thank you for opening this, the documentation is actually outdated and we will update it as soon as possible. 

The `CrashReporter` and `AutoTracking` modules are now available on SPM since there is now a way to make mixed-languages operate in a single target.

Regarding the second limitation, it is still there; although it shouldn't give you any troubles. 
The "issue" there is that SPM doesn't allow us to restrict one target to a specific platform. This means that you will be technically allowed by XCode to add an iOS specific module (like `TagManagement`) to a MacOS app, but then it will fail to compile.
This is not an issue, anyway, as you should never add an iOS specific module to a non iOS application in the first place. 
The limitation warning in the documentation is just there in case you do it by mistake and you don't recognize the compiler error.

Let me know if this solves your issues or if you have any more problems.

**Comment by Enricoza** [comment]
Hi @salvatoreboemia, the documentation will be updated shortly with the information that I provided in the previous comment. I'm going to close this for now, but feel free to re-open if something is still unclear.
