### ISSUE TITLE
Version 1.6.2 does not send tag requests

### ISSUE THREAD

**Issue by NickHughesDSW** [Tealium/tealium-swift#57]
After you removed the standard libs, no track calls are actually being made.  Verified with a network sniffer.  

Also, if you try to use an older release version, there is a carthage dependency cycle and will not build.

Not able to release with a tealium library.  As a service that we pay for, this is hard to believe that limited to no testing is being done.  Please try to submit an app to the App Store before releasing again.

**Comment by craigrouse** [comment]
@NickHughesDSW we are on it.

**Comment by craigrouse** [comment]
@NickHughesDSW I have just tested and I am seeing requests. Have you implemented the required [Consent Manager](https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Module-Consent-Manager/ta-p/24572) code? See also: https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Library-Release-Notes/ta-p/20568

If this doesn't help, please let me know and we will arrange a call with you to investigate.

**Comment by NickHughesDSW** [comment]
That is the issue, had to blacklist contentmanager.  I didnt see any documentation on this breaking change.  Any reason that the default is enabled for an EU based requirement?

**Comment by craigrouse** [comment]
@NickHughesDSW Glad it's sorted. The module is enabled by default, since that's the pattern that all the other modules follow in the library. We are working on improvements in this area. Let me know if you need any further assistance. I will close this issue for now. We appreciate your feedback, which will help inform our decisions for future releases.
